# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/idong-u/project/learn/과제/1/ui/User_Frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_User(object):
    def setupUi(self, User):
        User.setObjectName("User")
        User.resize(841, 491)
        self.ID = QtWidgets.QLabel(User)
        self.ID.setGeometry(QtCore.QRect(10, 10, 56, 12))
        self.ID.setObjectName("ID")
        self.ShowOrder = QtWidgets.QPushButton(User)
        self.ShowOrder.setGeometry(QtCore.QRect(760, 0, 75, 23))
        self.ShowOrder.setObjectName("ShowOrder")
        self.ShowCart = QtWidgets.QPushButton(User)
        self.ShowCart.setGeometry(QtCore.QRect(680, 0, 75, 23))
        self.ShowCart.setObjectName("ShowCart")
        self.Side_Frame = QtWidgets.QFrame(User)
        self.Side_Frame.setGeometry(QtCore.QRect(550, 30, 281, 441))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Side_Frame.sizePolicy().hasHeightForWidth())
        self.Side_Frame.setSizePolicy(sizePolicy)
        self.Side_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Side_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Side_Frame.setObjectName("Side_Frame")
        self.frame = QtWidgets.QFrame(User)
        self.frame.setGeometry(QtCore.QRect(10, 30, 531, 441))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ProductView = QtWidgets.QTableView(self.frame)
        self.ProductView.setGeometry(QtCore.QRect(0, 0, 531, 441))
        self.ProductView.setObjectName("ProductView")
        self.CartView = QtWidgets.QTableView(self.frame)
        self.CartView.setGeometry(QtCore.QRect(0, 0, 531, 441))
        self.CartView.setObjectName("CartView")
        self.OrderView = QtWidgets.QTableView(self.frame)
        self.OrderView.setGeometry(QtCore.QRect(0, 0, 531, 441))
        self.OrderView.setObjectName("OrderView")
        self.ShowProduct = QtWidgets.QPushButton(User)
        self.ShowProduct.setGeometry(QtCore.QRect(600, 0, 75, 23))
        self.ShowProduct.setObjectName("ShowProduct")

        self.retranslateUi(User)
        QtCore.QMetaObject.connectSlotsByName(User)

    def retranslateUi(self, User):
        _translate = QtCore.QCoreApplication.translate
        User.setWindowTitle(_translate("User", "Frame"))
        self.ID.setText(_translate("User", "사용자"))
        self.ShowOrder.setText(_translate("User", "주문목록"))
        self.ShowCart.setText(_translate("User", "장바구니"))
        self.ShowProduct.setText(_translate("User", "상품"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    User = QtWidgets.QFrame()
    ui = Ui_User()
    ui.setupUi(User)
    User.show()
    sys.exit(app.exec_())
