DROP TABLE IF EXISTS `OrderItems`;
DROP TABLE IF EXISTS `Recipe`;
DROP TABLE IF EXISTS `Inventory`;
DROP TABLE IF EXISTS `OrderList`;
DROP TABLE IF EXISTS `User`;
DROP TABLE IF EXISTS `Part`;
DROP TABLE IF EXISTS `Product`;
DROP TABLE IF EXISTS `CODE`;


CREATE TABLE `CODE` (
  `CODEID` varchar(100) NOT NULL,
  `CODE` varchar(100) DEFAULT NULL,
  `UPPER_CODE` varchar(100) DEFAULT NULL,
  `CODE_NAME` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`CODEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;


CREATE TABLE `Inventory` (
  `seq` int(11) NOT NULL AUTO_INCREMENT,
  `I_ID` varchar(100) DEFAULT NULL,
  `QUANTITY` varchar(100) DEFAULT NULL,
  `DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE `OrderList` (
  `U_ID` varchar(100) DEFAULT NULL,
  `STATE` varchar(100) DEFAULT NULL,
  `ORDER_DATE` datetime DEFAULT NULL,
  `COMP_DATE` datetime DEFAULT NULL,
  `ORDER_ID` varchar(100) NOT NULL,
  PRIMARY KEY (`ORDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE `Part` (
  `PPID` varchar(100) NOT NULL,
  `NAME` varchar(100) DEFAULT NULL,
  `PRICE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`PPID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE `Product` (
  `PID` varchar(100) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `PRICE` varchar(100) NOT NULL,
  `DES` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`PID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE `Recipe` (
  `P_ID` varchar(100) DEFAULT NULL,
  `PP_ID` varchar(100) DEFAULT NULL,
  `COUNT` int(11) DEFAULT NULL,
  `seq` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`seq`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE `User` (
  `IN_ID` varchar(100) NOT NULL,
  `ID` varchar(100) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `PASS` varchar(100) NOT NULL,
  `CODE` varchar(100) NOT NULL,
  PRIMARY KEY (`IN_ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE `OrderItems` (
  `ORDER_ID` varchar(100) DEFAULT NULL,
  `P_ID` varchar(100) DEFAULT NULL,
  `COUNT` varchar(100) DEFAULT NULL,
  KEY `ORDERITEMS_ORDER_ID_IDX` (`ORDER_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

