# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python\learn\python\pyqt\pyqt5\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1016, 769)
        self.button_run = QtWidgets.QPushButton(Dialog)
        self.button_run.setGeometry(QtCore.QRect(920, 410, 75, 23))
        self.button_run.setObjectName("button_run")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(230, 150, 761, 241))
        self.textEdit.setObjectName("textEdit")
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(30, 141, 151, 241))
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setObjectName("listView")
        self.button_rollback = QtWidgets.QPushButton(Dialog)
        self.button_rollback.setGeometry(QtCore.QRect(820, 410, 75, 23))
        self.button_rollback.setObjectName("button_rollback")
        self.button_commit = QtWidgets.QPushButton(Dialog)
        self.button_commit.setGeometry(QtCore.QRect(720, 410, 75, 23))
        self.button_commit.setObjectName("button_commit")
        self.button_clear = QtWidgets.QPushButton(Dialog)
        self.button_clear.setGeometry(QtCore.QRect(620, 410, 75, 23))
        self.button_clear.setObjectName("button_clear")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setEnabled(False)
        self.textBrowser.setGeometry(QtCore.QRect(20, 450, 981, 301))
        self.textBrowser.setObjectName("textBrowser")
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(10, 440, 991, 321))
        self.tableView.setObjectName("tableView")
        self.tableView.raise_()
        self.button_run.raise_()
        self.textEdit.raise_()
        self.listView.raise_()
        self.button_rollback.raise_()
        self.button_commit.raise_()
        self.button_clear.raise_()
        self.textBrowser.raise_()

        self.retranslateUi(Dialog)
        self.button_clear.clicked.connect(self.textEdit.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.button_run.setText(_translate("Dialog", "run"))
        self.button_rollback.setText(_translate("Dialog", "rollback"))
        self.button_commit.setText(_translate("Dialog", "commit"))
        self.button_clear.setText(_translate("Dialog", "clear"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">safdsafdsafdsafdsafdsafd</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">asfdsafdsafdsafd</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
