# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/idong-u/project/learn/과제/1/ui/Biz_Parts_SIde_Frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PartsSide(object):
    def setupUi(self, PartsSide):
        PartsSide.setObjectName("PartsSide")
        PartsSide.resize(281, 441)
        self.button_edit = QtWidgets.QPushButton(PartsSide)
        self.button_edit.setGeometry(QtCore.QRect(170, 400, 75, 23))
        self.button_edit.setObjectName("button_edit")
        self.gridLayoutWidget = QtWidgets.QWidget(PartsSide)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 261, 311))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.part_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.part_name.setObjectName("part_name")
        self.gridLayout.addWidget(self.part_name, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 3, 1, 1)
        self.part_price = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.part_price.setObjectName("part_price")
        self.gridLayout.addWidget(self.part_price, 1, 2, 1, 1)
        self.part_inventory_count = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.part_inventory_count.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.part_inventory_count.setMaximum(999999999)
        self.part_inventory_count.setObjectName("part_inventory_count")
        self.gridLayout.addWidget(self.part_inventory_count, 2, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)

        self.retranslateUi(PartsSide)
        QtCore.QMetaObject.connectSlotsByName(PartsSide)

    def retranslateUi(self, PartsSide):
        _translate = QtCore.QCoreApplication.translate
        PartsSide.setWindowTitle(_translate("PartsSide", "Frame"))
        self.button_edit.setText(_translate("PartsSide", "수정"))
        self.label_9.setText(_translate("PartsSide", ":"))
        self.label_2.setText(_translate("PartsSide", "부품명"))
        self.label_11.setText(_translate("PartsSide", ":"))
        self.label_6.setText(_translate("PartsSide", "원"))
        self.label_12.setText(_translate("PartsSide", "개"))
        self.label_8.setText(_translate("PartsSide", ":"))
        self.label_10.setText(_translate("PartsSide", "제고"))
        self.label_4.setText(_translate("PartsSide", "가격"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PartsSide = QtWidgets.QFrame()
    ui = Ui_PartsSide()
    ui.setupUi(PartsSide)
    PartsSide.show()
    sys.exit(app.exec_())
