# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/idong-u/project/learn/과제/1/ui/Biz_Frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Biz(object):
    def setupUi(self, Biz):
        Biz.setObjectName("Biz")
        Biz.resize(841, 491)
        self.ID = QtWidgets.QLabel(Biz)
        self.ID.setGeometry(QtCore.QRect(10, 10, 56, 12))
        self.ID.setObjectName("ID")
        self.ShowOrder = QtWidgets.QPushButton(Biz)
        self.ShowOrder.setGeometry(QtCore.QRect(760, 0, 75, 23))
        self.ShowOrder.setObjectName("ShowOrder")
        self.ShowParts = QtWidgets.QPushButton(Biz)
        self.ShowParts.setGeometry(QtCore.QRect(680, 0, 75, 23))
        self.ShowParts.setObjectName("ShowParts")
        self.Side_Frame = QtWidgets.QFrame(Biz)
        self.Side_Frame.setGeometry(QtCore.QRect(550, 30, 281, 441))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Side_Frame.sizePolicy().hasHeightForWidth())
        self.Side_Frame.setSizePolicy(sizePolicy)
        self.Side_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Side_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Side_Frame.setObjectName("Side_Frame")
        self.frame = QtWidgets.QFrame(Biz)
        self.frame.setGeometry(QtCore.QRect(10, 30, 531, 441))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ProductView = QtWidgets.QTableView(self.frame)
        self.ProductView.setGeometry(QtCore.QRect(0, 0, 531, 441))
        self.ProductView.setObjectName("ProductView")
        self.OrderView = QtWidgets.QTableView(self.frame)
        self.OrderView.setGeometry(QtCore.QRect(0, 0, 531, 441))
        self.OrderView.setObjectName("OrderView")
        self.PartsView = QtWidgets.QTableView(self.frame)
        self.PartsView.setGeometry(QtCore.QRect(0, 0, 531, 441))
        self.PartsView.setObjectName("PartsView")
        self.NewView = QtWidgets.QTabWidget(self.frame)
        self.NewView.setGeometry(QtCore.QRect(0, 0, 531, 441))
        self.NewView.setObjectName("NewView")
        self.NewProductTab = QtWidgets.QWidget()
        self.NewProductTab.setObjectName("NewProductTab")
        self.NewProductView = QtWidgets.QTableView(self.NewProductTab)
        self.NewProductView.setGeometry(QtCore.QRect(0, 0, 531, 421))
        self.NewProductView.setObjectName("NewProductView")
        self.NewView.addTab(self.NewProductTab, "")
        self.NewPartTab = QtWidgets.QWidget()
        self.NewPartTab.setObjectName("NewPartTab")
        self.NewPartView = QtWidgets.QTableView(self.NewPartTab)
        self.NewPartView.setGeometry(QtCore.QRect(-10, -10, 531, 421))
        self.NewPartView.setObjectName("NewPartView")
        self.NewView.addTab(self.NewPartTab, "")
        self.RecipeView = QtWidgets.QTableView(self.frame)
        self.RecipeView.setGeometry(QtCore.QRect(0, 0, 531, 441))
        self.RecipeView.setObjectName("RecipeView")
        self.ShowProduct = QtWidgets.QPushButton(Biz)
        self.ShowProduct.setGeometry(QtCore.QRect(600, 0, 75, 23))
        self.ShowProduct.setObjectName("ShowProduct")
        self.ShowNew = QtWidgets.QPushButton(Biz)
        self.ShowNew.setGeometry(QtCore.QRect(440, 0, 75, 23))
        self.ShowNew.setObjectName("ShowNew")
        self.ShowRecipe = QtWidgets.QPushButton(Biz)
        self.ShowRecipe.setGeometry(QtCore.QRect(520, 0, 75, 23))
        self.ShowRecipe.setObjectName("ShowRecipe")

        self.retranslateUi(Biz)
        self.NewView.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Biz)

    def retranslateUi(self, Biz):
        _translate = QtCore.QCoreApplication.translate
        Biz.setWindowTitle(_translate("Biz", "Frame"))
        self.ID.setText(_translate("Biz", "관리자"))
        self.ShowOrder.setText(_translate("Biz", "주문"))
        self.ShowParts.setText(_translate("Biz", "부품"))
        self.NewView.setTabText(self.NewView.indexOf(self.NewProductTab), _translate("Biz", "상품"))
        self.NewView.setTabText(self.NewView.indexOf(self.NewPartTab), _translate("Biz", "부품"))
        self.ShowProduct.setText(_translate("Biz", "상품"))
        self.ShowNew.setText(_translate("Biz", "신규"))
        self.ShowRecipe.setText(_translate("Biz", "상품구성편집"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Biz = QtWidgets.QFrame()
    ui = Ui_Biz()
    ui.setupUi(Biz)
    Biz.show()
    sys.exit(app.exec_())
