# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python\learn\과제\1\ui\Com_Frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Office(object):
    def setupUi(self, Office):
        Office.setObjectName("Office")
        Office.resize(841, 491)
        self.label = QtWidgets.QLabel(Office)
        self.label.setGeometry(QtCore.QRect(0, 0, 60, 12))
        self.label.setObjectName("label")

        self.retranslateUi(Office)
        QtCore.QMetaObject.connectSlotsByName(Office)

    def retranslateUi(self, Office):
        _translate = QtCore.QCoreApplication.translate
        Office.setWindowTitle(_translate("Office", "Frame"))
        self.label.setText(_translate("Office", "사무실사람"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Office = QtWidgets.QFrame()
    ui = Ui_Office()
    ui.setupUi(Office)
    Office.show()
    sys.exit(app.exec_())
