# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/idong-u/project/learn/과제/1/ui/User_OrderList_Side_Frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OrderListSide(object):
    def setupUi(self, OrderListSide):
        OrderListSide.setObjectName("OrderListSide")
        OrderListSide.resize(282, 441)
        self.order_cancle = QtWidgets.QPushButton(OrderListSide)
        self.order_cancle.setGeometry(QtCore.QRect(180, 400, 75, 23))
        self.order_cancle.setObjectName("order_cancle")
        self.gridLayoutWidget = QtWidgets.QWidget(OrderListSide)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 261, 312))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 3, 1, 1)
        self.order_items = QtWidgets.QTableView(self.gridLayoutWidget)
        self.order_items.setObjectName("order_items")
        self.gridLayout.addWidget(self.order_items, 1, 0, 1, 4)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setRowStretch(1, 1)

        self.retranslateUi(OrderListSide)
        QtCore.QMetaObject.connectSlotsByName(OrderListSide)

    def retranslateUi(self, OrderListSide):
        _translate = QtCore.QCoreApplication.translate
        OrderListSide.setWindowTitle(_translate("OrderListSide", "Frame"))
        self.order_cancle.setText(_translate("OrderListSide", "주문취소"))
        self.label_8.setText(_translate("OrderListSide", ":"))
        self.label_3.setText(_translate("OrderListSide", "123123123123123"))
        self.label_13.setText(_translate("OrderListSide", "2000"))
        self.label_12.setText(_translate("OrderListSide", "원"))
        self.label_2.setText(_translate("OrderListSide", "주문번호"))
        self.label_10.setText(_translate("OrderListSide", "총액"))
        self.label_11.setText(_translate("OrderListSide", ":"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OrderListSide = QtWidgets.QFrame()
    ui = Ui_OrderListSide()
    ui.setupUi(OrderListSide)
    OrderListSide.show()
    sys.exit(app.exec_())
