# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python\learn\과제\1\ui\User_Cart_Side_Frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CartSide(object):
    def setupUi(self, CartSide):
        CartSide.setObjectName("CartSide")
        CartSide.resize(281, 441)
        self.gridLayoutWidget = QtWidgets.QWidget(CartSide)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 261, 312))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 3, 1, 1)
        self.listView = QtWidgets.QListView(self.gridLayoutWidget)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 1, 0, 1, 4)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 2, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 2, 1, 1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(CartSide)
        self.pushButton_4.setGeometry(QtCore.QRect(180, 400, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(CartSide)
        QtCore.QMetaObject.connectSlotsByName(CartSide)

    def retranslateUi(self, CartSide):
        _translate = QtCore.QCoreApplication.translate
        CartSide.setWindowTitle(_translate("CartSide", "Frame"))
        self.label_7.setText(_translate("CartSide", "건"))
        self.label_8.setText(_translate("CartSide", ":"))
        self.label_3.setText(_translate("CartSide", "2"))
        self.label_13.setText(_translate("CartSide", "2000"))
        self.label_12.setText(_translate("CartSide", "원"))
        self.label_2.setText(_translate("CartSide", "선택한 상품"))
        self.label_10.setText(_translate("CartSide", "총액"))
        self.label_11.setText(_translate("CartSide", ":"))
        self.label_14.setText(_translate("CartSide", "수량 조절"))
        self.label_15.setText(_translate("CartSide", "개"))
        self.label_16.setText(_translate("CartSide", ":"))
        self.pushButton_4.setText(_translate("CartSide", "주문"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CartSide = QtWidgets.QFrame()
    ui = Ui_CartSide()
    ui.setupUi(CartSide)
    CartSide.show()
    sys.exit(app.exec_())
